### PR TITLE
Fix 'grammar' pluralization

### LINKED ISSUE #63: Wrong pluralization of 'grammar'
```js
var inflection = require('inflection');
console.log(inflection.pluralize('grammar'));
// "grammar" instead of expected "grammars"
```

I've seen that this package is based on wiktionary.
The grammar [page](https://en.wiktionary.org/wiki/grammar) does mention: _grammar (countable and uncountable, **plural grammars**)_

I noticed this when defining a 'grammar' model with the ORM Sequelize which has inflection as a dependency. Also, it seems that the issue comes from this package itself and not from rails.

### PR DESCRIPTION
**Pull request by eseliger**
`'grammar'` is countable, so it needs to be removed from the uncountable-words list.

Closes #63

### CODE REVIEW

**Comment by papb** [comment]
@ben-lin ping

**Comment by p-kuen** [comment]
@eseliger Thanks for the PR!
As I am a new maintainer for this package, I will have a look on this PR.

Could you please also provide a `singularize` test from `grammars` to `grammar`? I'll merge the PR as soon as possible then.

**Comment by eseliger** [comment]
There ya go :) Thanks for taking over ownership of this package 👍

**Review by p-kuen — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
